### ISSUE TITLE
Strange folder created using a different user

### ISSUE THREAD

**Issue by feed3r** [luca-c-xcv/gogs#4]
After the fix for using a different user (than the standard "git"), despite we have corrected all the creation script, still a new directory is created, called ~[USER_NAME], in the gogs main directory. 

This almost surely means that there still is a mkdir command that is not using the correct variable resolution, that need to be found and fixed.

**Comment by luca-c-xcv** [comment]
The bug has been fixed. The problem stemmed from `mkdir -p $USER_HOME` where `$USER_HOME` was set to `~[USER_NAME]`. The creation of this folder was unnecessary, so it was removed.

**Comment by luca-c-xcv** [comment]
Another bug was found. Instead of linking the `/data/[USER_NAME]` folder to `/home/[USER_NAME]` the `/data/git` folder had been linked to `/home/[USER_NAME]`. This bug has also been fixed by correcting the link.

**Comment by luca-c-xcv** [comment]
The next steps are testing each new feature

**Comment by feed3r** [comment]
Running GOGS with this new patch, a new error of form SIGSEGV occured. This occurs during the execution of hooks PostReceive, and it's probably linked to the error:

USERMOD - No Changes

shown during docker startup.

In particular, the issue seems to be linked to this function:

```
setids() {
    # export USER=$USER_GOGS
    PUID=${PUID:-1000}
    PGID=${PGID:-1000}
    groupmod -o -g "$PGID" $USER
    usermod -o -u "$PUID" $USER
}
```

present in start.sh. Here the USERID and GROUPID are fixed to the ones of git user (-1000). The solution is to retrieve UserId and GroupId dinamically and use them in this function.
